
pygments:         true
permalink:        pretty
markdown:         kramdown
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Indigo Sleep
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.indigosleep.com/
#
# 2. URL of this page
url:              http://1WorldStudios.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           4everbed
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/12bbLkw
  #
  # URL of a cover photo of your project
  cover_image:    dl.dropboxusercontent.com/s/6t3c8zr3teizz8v/indigo%20take%20a%20stand%20while%20you%20sleep.png
  #
  # Use a one-liner to describe your project
  description:    Indigo Sleep's 4everbed gives you two mattresses for the price of one!
#
# 4. Your Twitter handle
twitter_handle:   IndigoSleep
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  Hi from the Indigo Sleep team! <br />
  First of all, thank you for signing up to our mailing list. <br />
  We wanted to tell you that our project is now live on Kickstarter,
  and now we have to count on your support to not only back the project, but also share the love. ♥
